### ISSUE TITLE
a problem with array bounds in eval.cpp

### ISSUE THREAD

**Issue by HansLoehle** [Matthies/RubiChess#159]
Hi!

If I did not overlook something, the second array index `POPCOUNT(supporting) * 2 + (bool)phalanx` takes values in the range from 1 to 5 but should be one less.
This happens during the first position of the built in benchmark, when the calculations for depth 8 start.
the output of the program at this point is:
...
info depth 7 currmove g1h3  currmovenumber 19
info depth 7 currmove b2b3  currmovenumber 20
info depth 7 seldepth 8 multipv 1 time 6573 score cp 30  nodes 3703 nps 563 tbhits 0 hashfull 0 pv d2d3  g8f6  g1f3  d7d5  b1c3  c8f5  e2e3
info depth 8 currmove d2d3  currmovenumber 1

https://github.com/Matthies/RubiChess/blob/2e642b2bb0e012b67bf550346d6fcbcb86ecf040/RubiChess/eval.cpp#L306

a screenshot of Visual Studio's debugger:

![Schirmschuss_Rubi](https://user-images.githubusercontent.com/42576847/69578154-2d8c3900-0fd0-11ea-8f38-68c566c87c65.jpg)

Sincerly,
  Hans

**Comment by Matthies** [comment]
Interesting. I may have thought that thjere cannot be both two supporting pawns and a phalanx but of course with two stacked pawns the index can be 5. Lets see how many positions in my tuning sets will trigger this. I probably also need to retune the parameters following the eConnectedBonus cause their values are probably used instead with this bug.

Thanks for the report.

**Comment by Matthies** [comment]
The (not used) eConnectedBonus[r+1][0] steps in for the missing eConnectedBonus[r][5]. In the very last rank 7 the next parameter eBackwardpawnpenalty is used but this position would have two pawns on rank 7 and two more on rank 6 which gets probably enough score in any way.
So the bug is there but doesn't hurt strength. I'm testing a fix with correct bounds and retuned parameters and hope for no regression...
